version: "3.7"

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: doc_analyzer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - app-network

  app:
    build: .
    ports:
      - 5001:5001
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
